---
name: Call Validate PR Workflow
on:
  pull_request:
    branches: [main]
    paths:
      - 'src/pages/**'

jobs:
  call_validation:
    name: Validate PR
    uses: AdobeDocs/adp-devsite-workflow/.github/workflows/validate-pr.yml@DEVSITE-1978-linter-bug
